### PR TITLE
make lazy.vim instructions more clear

### PR DESCRIPTION
**Pull request by hubrix**
confused me when i tried to install, since lazy recommends structured config and the config in the readme showed for the older single file config

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by hubrix** [comment]
I was confused trying to set this up, so once I figured out what was confusing me I tried to rewrite the instructions to be more clear as I have seen from other plugins.

**Comment by olimorris** [comment]
Thanks for the PR. Can you also share the lazy guidelines you're referring to?

**Comment by hubrix** [comment]
Take a look here: https://lazy.folke.io/installation

**Comment by S1M0N38** [comment]
The majority of Neovim plugins listing lazy.nvim installation instruction in their readme.md do not include the `return` keyword. Even folke's plugins do not include it (e.g. [folke/tokionight](https://github.com/folke/tokyonight.nvim?tab=readme-ov-file#-installation)).

**Comment by hubrix** [comment]
Take a look at the documentation on "structuring"
https://lazy.folke.io/usage/structuring

That includes the return keyword in the example. And it is required for the
structured plugins setup that lazy seems to recommend as the default. The
configuration doesn't work without it

**Comment by S1M0N38** [comment]
You can have Structured Setup or Single File Setup (see https://lazy.folke.io/installation).

- When using structured setup, the config is split across multiple files, and every file is a source using the `require` keyword, so you have to return the plugin config as a Lua table.

- With a single file set, you put the plugin config table directly in the lazy.nvim setup function, and you do not need the return keyword.

I think that the README should only describe the lazy.nvim plugin config format.

**Comment by hubrix** [comment]
Listen, it's your project. I was just trying to be helpful since I was
confused getting it set up given the instructions provided. Feel free to
kill the change.

**Comment by olimorris** [comment]
Thanks so much @hubrix for your suggestion. For now, I'm going to leave it as-is and keep it as simple as possible.

**Pull request closed without merging**
