### PR TITLE
feat: better workflow

### PR DESCRIPTION
**Pull request by olimorris**
Users can now move between open chat buffers with `}` and `{`. There is prevention built into the plugin to stop multiple chat buffers being open at the same time. Global variables have also been reduced.

### CODE REVIEW

**Comment by olimorris** [comment]
@niba please try this PR out and let me know your thoughts

**Comment by niba** [comment]
Wow, that was fast! Thanks! I'll test it tomorrow and update this comment with feedback

**Comment by olimorris** [comment]
Looks like the keymaps in your config don't conform to the new API: https://github.com/olimorris/codecompanion.nvim/issues/9#issuecomment-2265075381

**Comment by niba** [comment]
I updated my config to the latest version. The version from the main branch works without problems. I even created pr #89 to fix some issues with the new config.

I also tried calling the command directly without using keymaps, and the effect is the same. I will double-check everything.

**Comment by olimorris** [comment]
That's odd. Could you share your complete config with me?

**Comment by niba** [comment]
I resolved the issue. You changed the callback names for header navigation, and I still had the old ones in my config. Sorry about that.

**Comment by olimorris** [comment]
Great spot! Yeah I need to do better in terms of breaking the config and making it easier for users to identify what's changed

**Comment by niba** [comment]
This is incredibly good. I tested all combinations, and everything works perfectly. Superb job!

The only nitpick I have is this scenario:

1. Open two chats: Chat 1 and Chat 2.
2. Destroy Chat 2 - **Question**: Should destroying a chat close the chat buffer or shift focus to the previous/next chat?
3. Destroying a chat closes it, leaving you in the code buffer. Use the toggle command to bring up the chat buffer again.
4. The toggle creates a new chat instead of focusing on existing one. This only happens when your last action in the chat buffer was to destroy a chat.

**Comment by niba** [comment]
Thanks!

Functionally, everything works, but there is one small visual detail. I have Treesitter context on my code buffer that renders a white line and function header. When I jump between chats, this line and header appear across the entire screen for a few milliseconds. I didn't notice this thing in the previous version.

Gif:
GifCode

**Comment by olimorris** [comment]
That seems really odd as it shouldn't technically draw the lines. I've just remove some debug statements that were there purely for testing...that's technically an I/O request if you have the log level at `debug` (I need to make that async!). Let me know if it continues.

**Comment by niba** [comment]
@olimorris  so I tested it this morning and this is still happenning

I manage to resolve it by changing the order of operations

```lua
    chats[index].chat:hide()
    chats[next].chat:open()

    to =>

    chats[next].chat:open()
    chats[index].chat:hide()
```

I also noticed that the width of my chat window jumps. You should probably try to read the current width and height of the window (if the chat is visible) and pass it to the open function, then try to reuse it inside"

**Comment by olimorris** [comment]
Bizarrely I only find the jumping occurs when the order is `open` and then `hide`. If you do `hide` and `open` it seems to be fine.

I believe that's because it's trying to open a chat buffer in the already open split. I'd advise playing around with the minimal.lua config in the bug report and seeing if that works. Could be a conflicting plugin. Also, I'm testing this on Nightly so may be something upstream in Neovim that is fixed.

**Comment by niba** [comment]
Hmm, that's weird. I want to clarify:
We have two different problems:

1. Flickering Treesitter context data
   - This is fixed by swapping hide and open.
2. Width and height of the chat window jumps
   - This started appearing when I swapped hide and open. I hadn't realized that I caused this bug, sorry.
  
When you mentioned 'jumping,' did you mean the second problem?

**Pull request merged**
