### PR TITLE
Add support for multiple buffer selection on /buffer slash command

### PR DESCRIPTION
**Pull request by andtankian**
## Description

This PR adds support for selecting multiple buffers when using the `/buffer` slash command with Telescope provider. Users can now select multiple buffers in Telescope and add their contents to the chat in a single operation.

## Screenshots

codecompanion

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by andtankian** [comment]
@olimorris 

Let me know if it needs adjustments.

**Comment by olimorris** [comment]
@andtankian this is awesome!! Thanks so much.

**Comment by amojury** [comment]
Could you tell me how to configure this feature in Telescope? Thanks. @andtankian

**Comment by andtankian** [comment]
@amojury 

This is my `codecompanion` setup with lazy:

```lua
{
  "olimorris/codecompanion.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-treesitter/nvim-treesitter",
    "hrsh7th/nvim-cmp", -- Optional: For using slash commands and variables in the chat buffer
    "nvim-telescope/telescope.nvim", -- Optional: For using slash commands
    { "stevearc/dressing.nvim", opts = {} }, -- Optional: Improves `vim.ui.select`
  },
  opts = {
    display = {
      chat = {
        show_header_separator = false,
      },
    },
    strategies = {
      chat = {
        adapter = "anthropic",
        slash_commands = {
          ["buffer"] = {
            opts = {
              provider = "telescope", //you need that part
            },
          },
        },
      },
      inline = {
        adapter = "anthropic",
      },
      agent = {
        adapter = "anthropic",
      },
    },
  },
}
```

**Pull request merged**
