### PR TITLE
tests: adding context visual selection tests

### PR DESCRIPTION
**Pull request by bassamsdata**
## Description

Added a test file for `context.lua`, focusing specifically on visual selection. While it could be improved, it's a solid starting point based on the current use cases for visual selection in the plugin.

## Related Issue(s)

#489

Thank you

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [x] I've updated the README and ran the `make docs` command

### CODE REVIEW

**Comment by olimorris** [comment]
Hey @bassamsdata. Sorry I haven't merged this yet. I wanted to move all tests to `mini.test` before I did. Feel free to port this yourself or I can amend this and incorporate.

**Comment by bassamsdata** [comment]
Hey @olimorris, thanks for the reply! I ported the file to `mini.test`.  

Out of curiosity, did you find `mini.test` better?

**Comment by olimorris** [comment]
Thank you @bassamsdata.

I've found Plenary to be very restrictive, especially when you need to do operations within Neovim. Not necessarily with CodeCompanion but with another plugin I maintain (a Neotest adapter). I also read a beautiful Reddit post where someone was recently talking about adding testing to their plugin using Mini.Test and how easy it was. So that was my hook.

Also, I'm becoming a big fan of the Mini suite of plugins. When you showed me Mini.Diff and I looked into its source code, I was impressed at how clean and simple it was. I'd looked at how Avante had implemented a diff and also looked at diffview.nvim and they were just so wildly complex for something that Neovim has natively.

Anyway, I'm hoping Mini.Test will make it much easier to start adding coverage for some of the UI features that have been breaking recently.

**Comment by bassamsdata** [comment]
Thank you for the informative response!  

> someone was recently talking about adding testing to their plugin using Mini.Test and how easy it was.


 I agree, it doesn’t require many changes as well, so that's a definite yes.  

> I was impressed at how clean and simple it was.

I had been trying to implement inline diffs in Neovim and explored Neogit’s diff functionality, which I still consider the most aesthetic and practical diff management, but it was very complex. Mini.Diff, on the other hand, was simple and a perfect addition for inline diffs.

**Pull request merged**
