### PR TITLE
fix(utils): should not use feedkeys to obtain current visual selection range

### PR DESCRIPTION
**Pull request by wenjinnn**
## Description

Use `gv` and `esc` feedkeys to obtain current visual selection range may cause problems for some plugins that listen to keyboard events, such as making mini.pick exit immediately in visual mode. 

## Related Issue(s)
Related to #375, this just fixed mini.pick problem when use it as vim.ui.select implement, haven't added mini.pick support to `display.action_palette.provider` yet.

Tested with following `minimal.lua` config
```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
      { "hrsh7th/nvim-cmp" },
      { "echasnovski/mini.pick" },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      opts = {
        log_level = "DEBUG",
      },
    },
  },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
    highlight = { enable = true },
  })
end

-- Setup completion
local cmp_status, cmp = pcall(require, "cmp")
if cmp_status then
  cmp.setup({
    mapping = cmp.mapping.preset.insert({
      ["<C-b>"] = cmp.mapping.scroll_docs(-4),
      ["<C-f>"] = cmp.mapping.scroll_docs(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.abort(),
      ["<CR>"] = cmp.mapping.confirm({ select = true }),
      -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
  })
end

-- setup ui.select
require('mini.pick').setup()
vim.ui.select = MiniPick.ui_select
```
## Screenshots
Before this PR:
before
after:
after

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by olimorris** [comment]
Thanks. Have you tested this for telescope and regular users?

**Comment by wenjinnn** [comment]
Yep. just tested these two situations.
after
after1

**Comment by olimorris** [comment]
Unfortunately, I'm finding that the context is not getting correctly updated. So when I select a small portion of text in the buffer, it's mistakenly selecting the whole buffer:

https://github.com/user-attachments/assets/687af991-fab0-441e-9b98-ccb25b729f36

**Comment by olimorris** [comment]
I looked at [Legendary.nvim's](https://github.com/search?q=repo%3Amrjones2014%2Flegendary.nvim%20nvim_replace_termcodes&type=code) implementation of how visual selections were passed to `vim.ui.select`.

**Comment by wenjinnn** [comment]
Strange. I selected the same line in the same `chat.lua`, and the problem did not occur. I will test it more.

**Comment by olimorris** [comment]
Also, do you have any reference material for why we shouldn't use feedkeys to obtain current visual selection?

**Comment by wenjinnn** [comment]
Sure. The description of this PR briefly explains the reason. To elaborate, it is because `mini.pick` listens for user keyboard input using the `getchatstr()` function after opening the picker panel, in [here](https://github.com/echasnovski/mini.nvim/blob/0a8a1072137d916406507c941698a4bfa9dbbe7a/lua/mini/pick.lua#L3422-L3426). For some reason, the action of opening the picker panel runs in parallel with `feedkeys` in `get_visual_selection`. As a result, immediately after the picker panel opens, `mini.pick` receives the `Esc` key input and closes itself right away.

In contrast, `vim.lsp.buf.code_action` in Neovim does not use this method to obtain the visual selection range. This PR references that [part](https://github.com/neovim/neovim/blob/05d9e6a9e850ee797a4a018e72156dd62831a4b6/runtime/lua/vim/lsp/buf.lua#L294-L308) of the code.

**Comment by wenjinnn** [comment]
> Unfortunately, I'm finding that the context is not getting correctly updated. So when I select a small portion of text in the buffer, it's mistakenly selecting the whole buffer:
> 
>  2024-10-30.09_43_35.-.WezTerm.mp4

It can be reproduced by using keymap to trigger `CodeCompanionActions`. It seems that the issue arises because it did not exit to normal mode, causing the position of the mark not refresh. 

> I looked at [Legendary.nvim's](https://github.com/search?q=repo%3Amrjones2014%2Flegendary.nvim%20nvim_replace_termcodes&type=code) implementation of how visual selections were passed to `vim.ui.select`.

Reference the code from Legendary.nvim to exit to normal mode, this problem looks like fixed for me.

**Comment by bassamsdata** [comment]
Hope you don’t mind me jumping in here, but I've had a tough time dealing with a similar issue. I discovered that using `'<` and `'>` can be unreliable, as they sometimes capture a previous selection, especially when triggered by a keymap.

For more consistent/reliable results, I'd recommend using:
```lua
vim.fn.getpos("v")
vim.fn.getpos(".")
```

So, I’d suggest the following approach, which works reliably and is similar to the PR. Of course, it could be modularized for reuse in other parts of the code:
```lua
  local start_pos = vim.fn.getpos("v")
  local end_pos = vim.fn.getpos(".")

  local start_line = start_pos[2]
  local start_col = start_pos[3]
  local end_line = end_pos[2]
  local end_col = end_pos[3]

  -- Normalize the range to start < end
  if
    start_line > end_line or (start_line == end_line and start_col > end_col)
  then
    start_pos, end_pos = end_pos, start_pos
    start_line, end_line = end_line, start_line
    start_col, end_col = end_col, start_col
  end
  -- Handle partial lines
  if #lines == 1 then
    lines[1] = lines[1]:sub(start_col, end_col)
  else
    lines[1] = lines[1]:sub(start_col)
    lines[#lines] = lines[#lines]:sub(1, end_col)
  end

```

**Comment by wenjinnn** [comment]
> Hope you don’t mind me jumping in here, but I've had a tough time dealing with a similar issue. I discovered that using `'<` and `'>` can be unreliable, as they sometimes capture a previous selection, especially when triggered by a keymap.希望你不介意我跳到这里，但我在处理类似的问题时遇到了困难。我发现使用`'<`和`'>`可能不可靠，因为它们有时会捕获先前的选择，尤其是在由键盘映射触发时。
> 
> For more consistent/reliable results, I'd recommend using:为了获得更一致/可靠的结果，我建议使用：
> 
> ```lua
> vim.fn.getpos("v")
> vim.fn.getpos(".")
> ```
> 
> So, I’d suggest the following approach, which works reliably and is similar to the PR. Of course, it could be modularized for reuse in other parts of the code:因此，我建议采用以下方法，该方法可靠且与 PR 类似。当然，它可以模块化以便在代码的其他部分重用：
> 
> ```lua
>   local start_pos = vim.fn.getpos("v")
>   local end_pos = vim.fn.getpos(".")
> 
>   local start_line = start_pos[2]
>   local start_col = start_pos[3]
>   local end_line = end_pos[2]
>   local end_col = end_pos[3]
> 
>   -- Normalize the range to start < end
>   if
>     start_line > end_line or (start_line == end_line and start_col > end_col)
>   then
>     start_pos, end_pos = end_pos, start_pos
>     start_line, end_line = end_line, start_line
>     start_col, end_col = end_col, start_col
>   end
>   -- Handle partial lines
>   if #lines == 1 then
>     lines[1] = lines[1]:sub(start_col, end_col)
>   else
>     lines[1] = lines[1]:sub(start_col)
>     lines[#lines] = lines[#lines]:sub(1, end_col)
>   end
> ```

Thank for the advice. But I tested with this snippet and find out it always return the very first line. Is there any mistake here? you can try it with this [branch](https://github.com/wenjinnn/codecompanion.nvim/tree/another-fix-selection-range)

**Comment by bassamsdata** [comment]
@wenjinnn, I assume the issue here is that some option is exiting visual mode before retrieving the text. The snippet I provided captures the text in visual mode consistently. I'll test the branch out and update here.

**Comment by olimorris** [comment]
The issue I had was with the explain prompt in the prompt library. Can we test that out.

**Comment by bassamsdata** [comment]
I think I found the issue, I'll update here shortly, just trying to make some more tests with edge cases.

**Comment by wenjinnn** [comment]
LGTM! I made some small changes regarding exiting visual mode, tested it with command and keymaps cases.

> The issue I had was with the explain prompt in the prompt library. Can we test that out.

Including this and fix code etc.
after2

**Comment by olimorris** [comment]
Hi both. Sorry I've responded to this.

What's the process to test this out?

**Comment by wenjinnn** [comment]
Hey @olimorris . The testing process is as follows:

1. Set `mini.pick` as the implementation of `ui.select`.
2. Enter visual mode in the buffer and select some text.
3. Enter command mode and execute `CodeCompanionActions`, verifying that the `ui.select` selection panel is displayed properly.
4. Choose an item from `Chat` | `Explain` | `Unit Tests` | `Fix code`, and test if the selected range is correctly passed to the codecompanion buffer.
5. Repeat step 3, but this time use a predefined keymap to execute `CodeCompanionActions`. Ensure the command produces the same result when executed from Command Mode and via keymap.
6. Set `telescope.nvim` as the implementation of `ui.select` and repeat steps 1-5 to confirm that `telescope.nvim` also works correctly.

**Comment by wenjinnn** [comment]
About this, please refer to my first comment. 
> ## Related Issue(s)
> Related to #375, this just fixed mini.pick problem when use it as vim.ui.select implement, haven't added mini.pick support to `display.action_palette.provider` yet.
To elaborate further, `ui.select` and `display.action_palette.provider` require different implementation approaches. and adde`mini_pick` to `display.action_palette.provider` need some additional work, I might submit another PR for this later

**Comment by olimorris** [comment]
Got it. I've tested this out and works fine. So happy to merge. Would love support for `mini.pick` with `display.action_palette.provider`.

**Pull request merged**
